# Copyright © Technologies Nexios TF Inc. — nexiostf.com
"""schema initial

Revision ID: 317439558236
Revises:
Create Date: 2026-06-11 19:15:24.127798
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "317439558236"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions requises (équivalent de create_database.sql).
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "andy_knowledge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("lang", sa.String(length=10), server_default="fr", nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_andy_knowledge_category", "andy_knowledge", ["category"], unique=False
    )
    op.create_index("idx_andy_knowledge_lang", "andy_knowledge", ["lang"], unique=False)
    op.create_table(
        "system_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "value_type", sa.String(length=20), server_default="string", nullable=False
        ),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_sensitive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section", "key", name="uq_system_config_section_key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("lang", sa.String(length=10), server_default="fr", nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("idx_users_is_active", "users", ["is_active"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("resource", sa.String(length=200), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_log_created_at", "audit_log", ["created_at"], unique=False
    )
    op.create_index("idx_audit_log_user_id", "audit_log", ["user_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column(
            "worker_models", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("merger_model", sa.String(length=200), nullable=True),
        sa.Column("processing_time", sa.Float(), nullable=True),
        sa.Column(
            "mode", sa.String(length=20), server_default="simple", nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversations_session", "conversations", ["session_id"], unique=False
    )
    op.create_index(
        "idx_conversations_user", "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_session_created",
        "messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "support_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "session_id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_support_conversations_session",
        "support_conversations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "user_totp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "recovery_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###

    # Configuration initiale (system_config) — équivalent de create_database.sql.
    system_config = sa.table(
        "system_config",
        sa.column("section", sa.String),
        sa.column("key", sa.String),
        sa.column("value", sa.Text),
        sa.column("value_type", sa.String),
        sa.column("label", sa.String),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(
        system_config,
        [
            {
                "section": "general",
                "key": "app_name",
                "value": "LLMUI Core",
                "value_type": "string",
                "label": "Nom application",
                "description": "Nom affiché dans l'interface",
            },
            {
                "section": "general",
                "key": "app_version",
                "value": "1.0.0",
                "value_type": "string",
                "label": "Version",
                "description": "Version courante",
            },
            {
                "section": "general",
                "key": "default_lang",
                "value": "fr",
                "value_type": "string",
                "label": "Langue par défaut",
                "description": "Code langue ISO",
            },
            {
                "section": "general",
                "key": "timezone",
                "value": "America/Montreal",
                "value_type": "string",
                "label": "Fuseau horaire",
                "description": "Timezone du serveur",
            },
            {
                "section": "andy",
                "key": "enabled",
                "value": "true",
                "value_type": "bool",
                "label": "Andy activé",
                "description": "Activer le widget Andy",
            },
            {
                "section": "andy",
                "key": "model",
                "value": "qwen3.5:0.8b",
                "value_type": "string",
                "label": "Modèle Ollama",
                "description": "Modèle utilisé par Andy",
            },
            {
                "section": "andy",
                "key": "ollama_url",
                "value": "http://localhost:11434",
                "value_type": "string",
                "label": "URL Ollama",
                "description": "Instance Ollama locale",
            },
            {
                "section": "security",
                "key": "totp_required_admin",
                "value": "true",
                "value_type": "bool",
                "label": "TOTP admin obligatoire",
                "description": "Exiger TOTP pour les admins",
            },
            {
                "section": "security",
                "key": "max_login_attempts",
                "value": "5",
                "value_type": "int",
                "label": "Max tentatives login",
                "description": "Blocage après N échecs",
            },
            {
                "section": "security",
                "key": "lockout_minutes",
                "value": "15",
                "value_type": "int",
                "label": "Durée blocage (min)",
                "description": "Durée blocage après échecs",
            },
            {
                "section": "security",
                "key": "cors_allowed_origins",
                "value": "[]",
                "value_type": "json",
                "label": "Origines CORS autorisées",
                "description": "Liste JSON des origines front-end autorisées (vide = même origine uniquement)",
            },
            {
                "section": "security",
                "key": "session_secret_key",
                "value": "",
                "value_type": "secret",
                "label": "Clé de session",
                "description": "Générée automatiquement au premier démarrage — ne pas éditer",
            },
            {
                "section": "security",
                "key": "totp_encryption_key",
                "value": "",
                "value_type": "secret",
                "label": "Clé de chiffrement TOTP",
                "description": "Générée automatiquement au premier démarrage — ne pas éditer",
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_totp")
    op.drop_index(
        "idx_support_conversations_session", table_name="support_conversations"
    )
    op.drop_table("support_conversations")
    op.drop_index("idx_messages_session_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_conversations_user", table_name="conversations")
    op.drop_index("idx_conversations_session", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("idx_audit_log_user_id", table_name="audit_log")
    op.drop_index("idx_audit_log_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_users_is_active", table_name="users")
    op.drop_table("users")
    op.drop_table("system_config")
    op.drop_index("idx_andy_knowledge_lang", table_name="andy_knowledge")
    op.drop_index("idx_andy_knowledge_category", table_name="andy_knowledge")
    op.drop_table("andy_knowledge")
    # ### end Alembic commands ###
